### PR TITLE
Fix issue #2 "Sourcemap is likely to be incorrect"

### PR DESCRIPTION
**Pull request by Tanimodori**
See detailed patch method in https://github.com/cawa-93/unplugin-auto-expose/issues/2#issuecomment-1192365216

### CODE REVIEW

**Comment by Tanimodori** [comment]
Note: This pr has been tested with [`vite-electron-builder`](https://github.com/cawa-93/vite-electron-builder) and no 'Sourcemap is likely to be incorrect' warning is shown.

**Comment by cawa-93** [comment]
Thanks for your input. Could you keep the original formatting? Just to not clutter up the commit history.

**Comment by Tanimodori** [comment]
I could reopen a pr for original formatting if you insist for keeping a clear git history. But most frontend repos use [prettier](https://prettier.io/) to automatically maintain code formatting, either by using the default prettier recommanded config or specify a prettier config by their own. Maintaining code format manually is a waste of time and is not friendly to online collaboration I think. Indent of 4 space is rarely seen nowadays and I think it is time to reformat by prettier now.

**Comment by cawa-93** [comment]
In any case, formatting changes must be separated from logic changes.  Now, looking through your PR, I can't even quickly find what significant changes have been made.  This makes the review process very difficult for anyone.

**Comment by Tanimodori** [comment]
Ok I'll open a more detailed pr then.

**Pull request closed without merging**
